물리적인 메모리상에 같이 뭉쳐버린다.
그래서 반복문없이 데이터배열에 대한 처리를 지원하여 빠르게 처리가능하다.

# 넘파이 설치 
    * pip install numpy

In [2]:
import numpy as np 

In [3]:
np.array([1,2,3])

array([1, 2, 3])

In [4]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [5]:
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [7]:
type(arr)

numpy.ndarray

In [9]:
arr=np.array([[1,2,3],
        [4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
type(arr)

numpy.ndarray

In [11]:
arr.shape

(2, 3)

In [17]:
arr=np.array([[[1,2,3],
              [4,5,6],
              [7,8,9]],
             [[10,11,12],
             [13,14,15],
             [16,17,18]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [18]:
type(arr)

numpy.ndarray

In [19]:
arr.shape

(2, 3, 3)