In [1]:
import numpy as np

In [41]:
import random

# 0과 1미만 사이의 랜덤값
print(random.random())

# 범위(1이상 10미만 중에 2간격으로 random값 - 정수값 return)
print(random.randrange(1, 10, 2))

# 범위(1이상 10 이하 - 정수값 return)
print(random.randint(1, 10))

0.429457716092024
9
1


#### rand : 0과 1사이의 랜던값(균등분포)

In [42]:
arr = np.random.rand(2, 3, 4)
print(arr)

[[[0.9258904  0.9248476  0.16424032 0.52246559]
  [0.90956675 0.95524832 0.48733488 0.12199887]
  [0.461664   0.44091613 0.23526671 0.21134719]]

 [[0.22758477 0.07273977 0.82753786 0.69820431]
  [0.04587656 0.14899749 0.58651114 0.60585713]
  [0.58363899 0.03376538 0.91424362 0.3671567 ]]]


#### randn : 정규분포, 가우시안 분포 난수값

In [43]:
arr = np.random.randn(2, 3, 4)
print(arr)

[[[-1.40018989  1.89938079 -0.7739513   0.4980407 ]
  [-1.94692797  0.83749396 -0.36733468 -0.06437258]
  [-0.03729854 -0.57735173  0.26952533 -0.33139808]]

 [[-1.35971135 -1.29690396  0.56467938 -1.78841773]
  [ 0.35081595 -0.35332501  0.90550873  1.93675996]
  [ 0.35583062  0.1394439  -0.66020285  0.10796598]]]


#### randint : 정수 난수 값 
- numpy.random.randint(low, high=None, size=None, dtype='I')
- low : 범위의 가장 낮은 값, 파라미터가 1개 일 경우 0 ~ low 까지
- high : 가장 높은 정수(선택사항)
- size : 반환 개수, array의 shapr형태 가능 -> size(3, 5)
- dtype : int

In [44]:
arr = np.random.randint(3, size=5)
print(arr)

[2 1 1 2 0]


In [45]:
arr = np.random.randint(3, 10, size=5)
print(arr)

[7 9 4 4 9]


In [51]:
arr = np.random.randint(3, 10, size=(3, 5))
print(arr)

[[7 5 9 4 9]
 [4 4 5 5 3]
 [4 9 4 6 3]]


- seed : 여러번 실행하여도 동일한 난수값

In [101]:
np.random.seed(6)
arr = np.random.randn(2, 3)
print(arr)

[[-0.31178367  0.72900392  0.21782079]
 [-0.8990918  -2.48678065  0.91325152]]


In [96]:
np.random.seed(35)
arr = np.random.randn(2, 3)
print(arr)

[[-1.88973671 -0.41359218 -0.76602601]
 [-0.92412667 -1.42159783  0.80525599]]
