In [2]:
import numpy as np

#### 인덱싱
- 단일 값 : 인덱스를 이용하여 하나의 데이터에 접근 
- 슬라이싱 : 연속된 인덱스를 이용하여 여러 데이터에 접근
- 팬시 인덱싱 : 리스트 형태의 인덱스를 이용하여 여러 데이터에 접근
- 불린 인덱싱 : 불링값의 리스트 형태의 인텍스를 이용하여 여러 데이터에 접근
    - 인덱스를 주면 차원이 감소하고 슬라이싱을 하면 차원이 유지 됨
    - https://darrengwon.tistory.com/657

#### 단일 값
- 1차원

In [5]:
arr = np.arange(1, 11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [6]:
arr[0]

1

In [7]:
arr[3]

4

In [8]:
arr[-1]

10

In [9]:
arr[-2]

9

In [10]:
arr[-2].ndim

0

In [11]:
arr.ndim

1

- 2차원

In [14]:
arr = np.arange(1, 10).reshape(3, -1)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
print(arr[0])

[1 2 3]


In [18]:
print(arr[0].shape)
print(arr[0].ndim)

(3,)
1


In [19]:
print(arr[0, 2])

3


In [21]:
print(arr[0, -1])

3


- 3차원

In [24]:
arr = np.arange(1, 9).reshape(2, 2, 2)
print(arr)
print(arr.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


In [26]:
print(arr[0])
print(arr[0].ndim)

[[1 2]
 [3 4]]
2


In [28]:
print(arr[0, 0])
print(arr[0, 0].ndim)

[1 2]
1


In [29]:
print(arr[1, 1, 1])

8


#### 슬라이싱

- 1차원

In [30]:
arr = np.arange(1, 11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [31]:
print(arr[1:5])

[2 3 4 5]


In [32]:
print(arr[2:])

[ 3  4  5  6  7  8  9 10]


In [33]:
print(arr[:8])

[1 2 3 4 5 6 7 8]


In [34]:
print(arr[:-2])

[1 2 3 4 5 6 7 8]


In [35]:
print(arr[1:5].ndim)

1


- 2차원

In [52]:
arr = np.arange(16).reshape(4, -1)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [56]:
print(arr[1:3, 1:3])
print(arr[1:3, 1:3].shape)
print(arr[1:3, 1:3].ndim)

[[ 5  6]
 [ 9 10]]
(2, 2)
2


In [57]:
print(arr[2, 1:3])

[ 9 10]


10, 11, 14, 15 / 9, 10, 11 / 5, 9 / 4, 5, 6, 7

- 3차원

In [58]:
arr = np.arange(27).reshape(3, 3, 3)
print(arr)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [59]:
print(arr[0:2, 0:2, 0:2])

[[[ 0  1]
  [ 3  4]]

 [[ 9 10]
  [12 13]]]


In [60]:
print(arr[2, 0:2, 0:2])

[[18 19]
 [21 22]]


In [64]:
print(arr[:, :, :2])

[[[ 0  1]
  [ 3  4]
  [ 6  7]]

 [[ 9 10]
  [12 13]
  [15 16]]

 [[18 19]
  [21 22]
  [24 25]]]


#### 팬시인덱싱

- 1차원

In [66]:
arr = np.arange(1, 11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [70]:
arr[8]

9

In [71]:
arr[1:5]

array([2, 3, 4, 5])

In [ ]:
arr[[2, 5, 8]]

- 2차원

In [72]:
arr = np.arange(1, 10).reshape(3, -1)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [77]:
print(arr[[0, 2], 2])

[3 9]


#### 불린 인덱싱

In [78]:
arr = np.arange(1, 11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [79]:
arr > 3

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [91]:
mask_1 = arr > 3
print(mask_1)

[False False False  True  True  True  True  True  True  True]


In [ ]:
[False False False  True  True  True  True  True  True  True]

In [90]:
arr[[False, False, False,  True,  True,  True,  True,  True,  True,  True]]

array([ 4,  5,  6,  7,  8,  9, 10])

In [92]:
arr[mask_1]

array([ 4,  5,  6,  7,  8,  9, 10])

In [93]:
arr[arr > 3]

array([ 4,  5,  6,  7,  8,  9, 10])

#### 여러조건
    - and : &
    - or : |

In [96]:
mask2 = (arr > 3) & (arr < 7)
print(mask2)

[False False False  True  True  True False False False False]


In [97]:
arr[mask2]

array([4, 5, 6])

In [98]:
arr[(arr > 3) & (arr < 7)]

array([4, 5, 6])