In [1]:
import numpy as np

#### 연산 
- add
- subtract
- multiply
- divide

- add

In [2]:
arr1 = np.arange(1, 11).reshape(2, 5)
print(arr1)
arr2 = np.random.randint(1, 10, size=10).reshape(2, 5)
print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[2 8 6 8 4]
 [7 3 2 6 2]]


In [3]:
print(arr1 + arr2)

[[ 3 10  9 12  9]
 [13 10 10 15 12]]


In [4]:
print(np.add(arr1, arr2))

[[ 3 10  9 12  9]
 [13 10 10 15 12]]


In [5]:
arr3 = arr2.reshape(5, 2)
print(arr3)

[[2 8]
 [6 8]
 [4 7]
 [3 2]
 [6 2]]


In [6]:
arr1 + arr3

ValueError: operands could not be broadcast together with shapes (2,5) (5,2) 

In [7]:
arr1 - arr2

array([[-1, -6, -3, -4,  1],
       [-1,  4,  6,  3,  8]])

In [8]:
np.subtract(arr1, arr2)

array([[-1, -6, -3, -4,  1],
       [-1,  4,  6,  3,  8]])

In [9]:
arr1 * arr2

array([[ 2, 16, 18, 32, 20],
       [42, 21, 16, 54, 20]])

In [10]:
np.multiply(arr1, arr2)

array([[ 2, 16, 18, 32, 20],
       [42, 21, 16, 54, 20]])

In [12]:
arr1 / arr2

array([[0.5       , 0.25      , 0.5       , 0.5       , 1.25      ],
       [0.85714286, 2.33333333, 4.        , 1.5       , 5.        ]])

In [13]:
np.divide(arr1, arr2)

array([[0.5       , 0.25      , 0.5       , 0.5       , 1.25      ],
       [0.85714286, 2.33333333, 4.        , 1.5       , 5.        ]])

#### 브로드캐스팅
- 개요
    - 출처: https://sacko.tistory.com/16 [데이터 분석하는 문과생, 싸코]
    - 어떤 조건만 만족한다면 모양이 다른 배열끼리의 연산도 가능하게 해주며 모양이 부족한 부분은 확장하여 연산을 수행할 수 있도록 한다는 것
    - ![](http://www.astroml.org/_images/fig_broadcast_visual_1.png)

```
정리하면,
브로드캐스팅(Broadcasting)은 모양이 다른 배열들 간의 연산이 어떤 조건을 만족했을 때 가능해지도록 배열을 자동적으로 변환하는 것이라고 정의할 수 있다. 그리고 누락되었거나 길이가 1인 차원에 대해 브로드캐스팅이 수행된다.

위의 세 그림은 배열 연산에서 항상 1차원 배열이 포함되어 있다. 그리고 행/열의 어떤 축이든(;0번/1번 어떤 축이든) 차원의 길이가 같은 것을 알 수 있다. 3x3 + 1x3,  3x1 + 1x3

브로드캐스팅이 일어날 수 있는 조건은 다음과 같다.
차원의 크기가 1일때 가능하다
두 배열 간의 연산에서 최소한 하나의 배열의 차원이 1이라면(0번 축이든 1번 축이든; 1행이든 1열이든) 가능하다.
차원의 짝이 맞을 때 가능하다
차원에 대해 축의 길이가 동일하면 브로드캐스팅이 가능하다.


출처: https://sacko.tistory.com/16 [데이터 분석하는 문과생, 싸코]
```

In [16]:
arr1 = np.arange(3)
print(arr1)

[0 1 2]


In [18]:
print(arr1 + 5)
print(arr1 - 5)

[5 6 7]
[-5 -4 -3]


In [19]:
# (3,3) + (3,)
arr1 = np.arange(1, 10).reshape(3,3)
print(arr1)
arr2 = np.arange(3)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[0 1 2]


In [21]:
print(arr1 + arr2)
print(arr1 * arr2)

[[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]]
[[ 0  2  6]
 [ 0  5 12]
 [ 0  8 18]]


In [22]:
# (3, 1) + (1, 3)
arr1 = np.arange(3).reshape(3,1)
print(arr1)
arr2 = np.arange(3)
print(arr2)

[[0]
 [1]
 [2]]
[0 1 2]


In [23]:
print(arr1 + arr2)

[[0 1 2]
 [1 2 3]
 [2 3 4]]
