In [1]:
import numpy as np

#### 통계
- mean

In [2]:
arr1 = np.random.rand(10).reshape(2, 5)
print(arr1)

[[0.26062992 0.49284183 0.44792143 0.52886801 0.863245  ]
 [0.50523251 0.45558647 0.7096893  0.39900109 0.45272466]]


In [3]:
np.mean(arr1)

0.5115740229784891

In [4]:
arr1.mean()

0.5115740229784891

- max, min, argmax : 가장 큰 값의 index, argmin : 가장 작은 값의 index
- argmax, argmin은 다차원이어도 1차원형태의 index를 반환 함

In [6]:
np.max(arr1)

0.8632450024862983

In [7]:
arr1.max()

0.8632450024862983

In [8]:
np.argmax(arr1)

4

In [9]:
arr1.argmax()

4

In [10]:
np.min(arr1)

0.26062991842667593

In [11]:
arr1.min()

0.26062991842667593

In [13]:
# 가장 작은 값의 index
arr1.argmin()

0

- median : 중앙값, std : 표준편차, var : 분산

In [14]:
# 중앙값
np.median(arr1)

0.47421415221465685

In [15]:
# 표준편차
np.std(arr1)

0.158084612607762

In [16]:
# 분산
np.var(arr1)

0.024990744743346185

#### 합계
- sum : 전체 합계, cumsum : 누적합계

In [17]:
arr2 = np.arange(10).reshape(2, 5)
print(arr2)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [18]:
np.sum(arr2)

45

In [19]:
np.cumsum(arr2)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [20]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [21]:
# sum에서 shift + tab => axis
np.sum(arr)

45

In [24]:
np.sum(arr, axis=0)

45

- 2차원

In [26]:
arr = np.arange(12).reshape(3, 4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


##### 행방향 (row) => 방향으로 더한다. 행을 더하는 것이 아니라 행 방향으로

In [29]:
# 행방향 (row) => 방향으로 더한다. 행을 더하는 것이 아니라 행 방향으로
print(np.sum(arr, axis=0))

[12 15 18 21]


In [31]:
# 열방향(column)
print(np.sum(arr, axis=1))

[ 6 22 38]


- 3차원

In [32]:
arr = np.arange(24).reshape(2, 3, 4)
print(arr)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


- axis => 0, 1, 2
- shape(2, 3, 4)
- 해당하는 위치의 shape가 사라지고 나머지 형태의 shape가 남는다.
- 예를 들어 axis가 0이면 shape(2, 3, 4)중 첫번째 2가 사라지고 (3, 4) 형태가 남는다

In [34]:
# axis = 0
# z축 방향
# 0 + 12, 1 + 13, 2 + 14
# (3, 4)가 남는다
print(np.sum(arr, axis=0))

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]


In [35]:
# axis = 1
# 행(row) 방향
# 0 + 4 + 8, 1 + 5 + 9, 12,... 16 + 20, 13 + 17 + 21, ...
# (2, 4)가 남는다
print(np.sum(arr, axis=1))

[[12 15 18 21]
 [48 51 54 57]]


In [36]:
# axis = 2
# 열(column) 방향
# 0 + 1 + 2 + 3, 4 + 5 + 6 + 7, ,... 12 + 13, 14 + 15, ...
# (2, 3)가 남는다
print(np.sum(arr, axis=2))

[[ 6 22 38]
 [54 70 86]]


#### any, all, where
 - any: 최소 하나 이상 조건을 만족하면 True, 모두 만족하지 않으면 False
 - all: 모든 원소가 조건을 만족하면 True, 하나라도 만족하지 않으면 False
 - where : 조건에 의해 값을 선택

In [37]:
arr = np.arange(1, 11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [50]:
print(arr > 5)
print(arr > 10)
print(arr < 11)

[False False False False False  True  True  True  True  True]
[False False False False False False False False False False]
[ True  True  True  True  True  True  True  True  True  True]


In [51]:
np.any(arr > 5)

True

In [52]:
np.any(arr > 10)

False

In [53]:
np.all(arr > 5)

False

In [54]:
np.all(arr > 10)

False

In [55]:
np.all(arr < 11)

True

#### np.where 참조자료 : https://m.blog.naver.com/bosongmoon/221791527433

In [56]:
# 조건에 맞는 index 를 반환
np.where(arr > 5)

(array([5, 6, 7, 8, 9], dtype=int64),)

In [57]:
# 팬시 indexing
arr[np.where(arr > 5)]

array([ 6,  7,  8,  9, 10])

In [58]:
# 조건에 맞으면 True, 틀리면 False
np.where(arr > 5, True, False)

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [47]:
print(np.where(arr > 5, arr, 0))

[ 0  0  0  0  0  6  7  8  9 10]


In [59]:
print(np.where(arr > 10, arr, 0))

[0 0 0 0 0 0 0 0 0 0]


In [60]:
print(np.where(arr < 11, arr, 0))

[ 1  2  3  4  5  6  7  8  9 10]
